// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1eKTikChOSpRExWSjoT9iIv7nmpM9tYk',
    appId: '1:479513021796:web:ead0cc146ade7b39ccfe71',
    messagingSenderId: '479513021796',
    projectId: 'matchup-football',
    authDomain: 'matchup-football.firebaseapp.com',
    storageBucket: 'matchup-football.firebasestorage.app',
    measurementId: 'G-1NYZDLEVGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYy5K31EUDJwbCxq3NYbzyapEtqg106O4',
    appId: '1:479513021796:android:90b965913cd8c457ccfe71',
    messagingSenderId: '479513021796',
    projectId: 'matchup-football',
    storageBucket: 'matchup-football.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr4mHcB8VPCWS_LLNUx2X9qb7RuOOi_94',
    appId: '1:479513021796:ios:08996e1c4c34cf83ccfe71',
    messagingSenderId: '479513021796',
    projectId: 'matchup-football',
    storageBucket: 'matchup-football.firebasestorage.app',
    iosBundleId: 'com.example.flutterRecipesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr4mHcB8VPCWS_LLNUx2X9qb7RuOOi_94',
    appId: '1:479513021796:ios:08996e1c4c34cf83ccfe71',
    messagingSenderId: '479513021796',
    projectId: 'matchup-football',
    storageBucket: 'matchup-football.firebasestorage.app',
    iosBundleId: 'com.example.flutterRecipesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1eKTikChOSpRExWSjoT9iIv7nmpM9tYk',
    appId: '1:479513021796:web:12d92b30fb037332ccfe71',
    messagingSenderId: '479513021796',
    projectId: 'matchup-football',
    authDomain: 'matchup-football.firebaseapp.com',
    storageBucket: 'matchup-football.firebasestorage.app',
    measurementId: 'G-34B43YV8H0',
  );
}
