// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUtpI9H5ZXS4beR_jHsGdtlVYn7-j_Lwo',
    appId: '1:885728878370:web:0d7048cf6ad0c722a7cf7b',
    messagingSenderId: '885728878370',
    projectId: 'recipesapp-d3bf3',
    authDomain: 'recipesapp-d3bf3.firebaseapp.com',
    storageBucket: 'recipesapp-d3bf3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX6q-LoK-PC6JWZd7Zee-4tqnjNOyg_Sg',
    appId: '1:885728878370:android:f69ed305a8dcc0d5a7cf7b',
    messagingSenderId: '885728878370',
    projectId: 'recipesapp-d3bf3',
    storageBucket: 'recipesapp-d3bf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE5nRGT1LQcerWUUNyAmgHIPbNtY6lmj4',
    appId: '1:885728878370:ios:fcf611dca11e28b3a7cf7b',
    messagingSenderId: '885728878370',
    projectId: 'recipesapp-d3bf3',
    storageBucket: 'recipesapp-d3bf3.appspot.com',
    iosBundleId: 'com.example.flutterRecipesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE5nRGT1LQcerWUUNyAmgHIPbNtY6lmj4',
    appId: '1:885728878370:ios:fcf611dca11e28b3a7cf7b',
    messagingSenderId: '885728878370',
    projectId: 'recipesapp-d3bf3',
    storageBucket: 'recipesapp-d3bf3.appspot.com',
    iosBundleId: 'com.example.flutterRecipesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUtpI9H5ZXS4beR_jHsGdtlVYn7-j_Lwo',
    appId: '1:885728878370:web:72561d2583b6dc86a7cf7b',
    messagingSenderId: '885728878370',
    projectId: 'recipesapp-d3bf3',
    authDomain: 'recipesapp-d3bf3.firebaseapp.com',
    storageBucket: 'recipesapp-d3bf3.appspot.com',
  );

}